apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck
  namespace: go-demo
spec:
  selector:
    matchLabels:
      app: healthcheck
      type: cmd
  template:
    metadata:
      labels:
        app: healthcheck
      type: cmd
    spec:
      containers:
      - name: healthcheck
        image: zephinzer/demo-healthcheck:latest
        envFrom:
          - configMapRef:
              name: healthcheck
        resources:
          limits:
            memory: "16Mi"
            cpu: "16m"
        ports:
        - containerPort: 11114

---

apiVersion: v1
kind: Service
metadata:
  name: healthcheck
  namespace: go-demo
spec:
  selector:
    app: healthcheck
    type: cmd
  ports:
  - port: 11114
    targetPort: 11114

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcheck
  namespace: go-demo
data:
  HEALTHY: "true"
  READY: "true"
