# apply this for kiali to work

apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  # it's: "username" (run "printf -- 'dXNlcm5hbWU=' | base64 -d" to check)
  username: dXNlcm5hbWU=
  # it's: "password" (run "printf -- 'cGFzc3dvcmQ=' | base64 -d" to check)
  passphrase: cGFzc3dvcmQ=
