# apply this for kiali to work

apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  username: dXNlcm5hbWU=
  passphrase: cGFzc3dvcmQ=
