apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:1.1.3
          imagePullPolicy: IfNotPresent
          command: ["vault", "server", "-config", "/vault/config/config.hcl"]
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          resources:
            limits:
              memory: "192Mi"
              cpu: "300m"
            requests:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config/config.hcl
              subPath: config.hcl
            - name: vault-tls
              mountPath: /etc/tls
          ports:
            - containerPort: 8200
              name: ui-port
        - name: consul-agent
          image: consul:1.5.1
          imagePullPolicy: IfNotPresent
          env:
            - name: GOSSIP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: consul
                  key: gossip-encryption-key
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "agent"
            - "-datacenter=dc1"
            - "-disable-host-node-id"
            - "-domain=cluster.local"
            - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
            - "-node=vault-1"
            - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
          resources:
            limits:
              memory: "192Mi"
              cpu: "300m"
            requests:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: consul-config
              mountPath: /consul/conf.d
            - name: consul-tls
              mountPath: /etc/tls
      volumes:
        - name: consul-config
          configMap:
            name: consul
        - name: vault-config
          configMap:
            name: vault
        - name: consul-tls
          secret:
            secretName: consul
        - name: vault-tls
          secret:
            secretName: vault