# deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator2
  namespace: go-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traffic-generator2
      type: cmd
  template:
    metadata:
      labels:
        app: traffic-generator2
        type: cmd
    spec:
      containers:
      - name: traffic-generator2
        image: zephinzer/demo-traffic-generator:latest
        env:
          - name: NAME
            value: traffic-generator2
          - name: URL
            value: http://fwdserver:11112/echoserver2
        envFrom:
          - configMapRef:
              name: traffic-generator
        resources:
          requests:
            memory: 20Mi
            cpu: 10m
          limits:
            memory: 50Mi
            cpu: 30m
