# https://gitlab.com/charts/gitlab/blob/master/examples/values-minikube.yaml
global:
  ingress:
    configureCertmanager: false
    class: "nginx"
  namespace: gitlab
  hosts:
    domain: 192.168.99.100.nip.io
    externalIP: 192.168.99.100
# Don't use certmanager, we'll self-sign
certmanager:
  install: false
# Use the `ingress` addon, not our Ingress (can't map 22/80/443)
nginx-ingress:
  enabled: false
# GitLab Runner isn't a big fan of self-signed certificates
gitlab-runner:
  install: false
