version: "3.5"
services:
  echoserver1:
    build:
      args:
        BIN_NAME: echoserver
      context: ../../build/bin
      dockerfile: ../../deployments/Dockerfile
    image: zephinzer/demo-echoserver:latest
    environment:
      NAME: "echoserver1"
    ports:
      - 11111:11111
    volumes:
      - ../../assets/certs/server.crt:/etc/ssl/server.crt:ro
      - ../../assets/keys/server.key:/etc/ssl/server.key:ro
  echoserver2:
    build:
      args:
        BIN_NAME: echoserver
      context: ../../build/bin
      dockerfile: ../../deployments/Dockerfile
    image: zephinzer/demo-echoserver:latest
    environment:
      NAME: "echoserver2"
    ports:
      - 11112:11111
    volumes:
      - ../../assets/certs/server.crt:/etc/ssl/server.crt:ro
      - ../../assets/keys/server.key:/etc/ssl/server.key:ro
  echoserver3:
    build:
      args:
        BIN_NAME: echoserver
      context: ../../build/bin
      dockerfile: ../../deployments/Dockerfile
    image: zephinzer/demo-echoserver:latest
    environment:
      NAME: "echoserver3"
    ports:
      - 11113:11111
    volumes:
      - ../../assets/certs/server.crt:/etc/ssl/server.crt:ro
      - ../../assets/keys/server.key:/etc/ssl/server.key:ro
  fwdserver:
    build:
      args:
        BIN_NAME: fwdserver
      context: ../../build/bin
      dockerfile: ../../deployments/Dockerfile
    image: zephinzer/demo-fwdserver:latest
    environment:
      NAME: "fwdserver"
      # access below with https://localhost:12111/echoserver1
      ECHOSERVER1: https://echoserver1:11111
      # access below with https://localhost:12111/echoserver2
      ECHOSERVER2: https://echoserver2:11111
    ports:
      - 12111:11111
    volumes:
      - ../../assets/certs/server.crt:/etc/ssl/server.crt:ro
      - ../../assets/keys/server.key:/etc/ssl/server.key:ro
  healthcheck:
    build:
      args:
        BIN_NAME: healhcheck
      context: ../../build/bin
      dockerfile: ../../deployments/Dockerfile
    image: zephinzer/demo-healhcheck:latest
    environment:
      NAME: "healhcheck"
    ports:
      - 13111:11111
    volumes:
      - ../../assets/certs/server.crt:/etc/ssl/server.crt:ro
      - ../../assets/keys/server.key:/etc/ssl/server.key:ro
  traffic-generator:
    build:
      args:
        BIN_NAME: traffic-generator
      context: ../../build/bin
      dockerfile: ../../deployments/Dockerfile
    image: zephinzer/demo-traffic-generator:latest
    environment:
      NAME: "traffic-generator"
      BODY: "{\"hello\":\"world\"}"
      METHOD: "POST"
      REQUEST_CONCURRENCY: 1
      REQUEST_INTERVAL: 3s
      REQUEST_RATE: 1
      URL: "https://echoserver3:11111"
    ports:
      - 14111:11111
